### ISSUE TITLE
TypeError: Object #<Object> has no method 'split'

### ISSUE THREAD

**Issue by cwallsfdc** [stomita/node-salesforce#24]
Idea?

$ sfjs

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'split'
    at Interface.setPrompt (readline.js:121:24)
    at new REPLServer (repl.js:128:7)
    at Object.start (repl.js:251:14)
    at Object.start (/usr/local/lib/node_modules/node-salesforce/lib/repl.js:88:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-salesforce/bin/sfjs:4:14)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)

**Comment by stomita** [comment]
Not reproduced in my env. Please tell your environment detail (like node ver, OS)
