### ISSUE TITLE
Cannot read property 'async' of undefined

### ISSUE THREAD

**Issue by rchampeimont** [stomita/node-salesforce#30]
Hello,

I have installed node-salesforce, but when I try to load the package I get the following error:

```
> require('node-salesforce')
TypeError: Cannot read property 'async' of undefined
    at /Users/raphael/nodejs-doctrine/node_modules/node-salesforce/node_modules/async/lib/async.js:8:30
    at Object.<anonymous> (/Users/raphael/nodejs-doctrine/node_modules/node-salesforce/node_modules/async/lib/async.js:692:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/raphael/nodejs-doctrine/node_modules/node-salesforce/node_modules/async/index.js:3:18)
    at Module._compile (module.js:409:26)
> 
```

**Comment by rchampeimont** [comment]
OK I have just seen that this module is deprecated. Bad luck that NPM website gives this one as its first result when you search for salesforce
